[buildpack]
name = "PHP"

	[publish.Ignore]
	files = [
		".github/",
		".gitignore",
		".rspec_parallel",
		"support/build/_*/",
		"support/devcenter/",
		"test/",
		"Gemfile",
		"Gemfile.lock",
		"hatchet.json",
		"hatchet.lock",
		"requirements.txt",
	]
